### ISSUE TITLE
Split up Button.tsx into Button and Anchor element with shared logic

### ISSUE THREAD

**Issue by timdujardin** [ioulian/next-ui-ghent-app-starter#13]
In that way, we can configure axe-linter.yml with 2 separate mappings.

```
global-components:
  Button:
    element: button
    attributes:
      - aria-*
  Anchor:
    element: a
    attributes:
      - aria-*
```

To remove:

- As

Shared logic:

- Variant
- Size
- FullWidth
- IconOnly ⚠️: This scenario must be covered by https://dequeuniversity.com/rules/axe/4.3/button-name.
- IconBefore
- IconAfter

Button logic:

- Disabled
- IsLoading ⚠️: The loading state should be communication through aria-live: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Loading/Loading.tsx.

Anchor logic:

- No specifics here
